### ISSUE TITLE
 [BadMethodCallException] Method setBackendUri does not exist.

### ISSUE THREAD

**Issue by noxify** [rinvex/cluster-installer#8]
Hi,

after a long time I found some minutes to try your installer package :)

But with my setup it doesn't work.

After installation and configuration I got an error while running

```
php artisan vendor:publish
```

The error message is the following:

```
[2016-04-18 19:09:55] local.ERROR: BadMethodCallException: Method setBackendUri does not exist. in /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:81
Stack trace:
#0 /Applications/MAMP/htdocs/rinvex/vendor/cluster/foundation/src/Providers/ClusterServiceProvider.php(157): Illuminate\Routing\UrlGenerator->__call('setBackendUri', Array)
#1 /Applications/MAMP/htdocs/rinvex/vendor/cluster/foundation/src/Providers/ClusterServiceProvider.php(73): Cluster\Foundation\Providers\ClusterServiceProvider->setBackendUri()
#2 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(531): Cluster\Foundation\Providers\ClusterServiceProvider->register()
#3 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(Cluster\Foundation\Providers\ClusterServiceProvider))
#4 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(507): Illuminate\Foundation\ProviderRepository->load(Array)
#5 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#6 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#7 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#8 /Applications/MAMP/htdocs/rinvex/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#9 /Applications/MAMP/htdocs/rinvex/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 {main}  
```

My `composer.json` is the following:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "cluster/installer": "dev-develop"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```

in the `config/app.php` i have added the following to the providers and aliases:

```
'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        //...
        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        Cluster\Foundation\Providers\ClusterServiceProvider::class,
        Cluster\Installer\Providers\InstallerServiceProvider::class

    ],

 'aliases' => [

       //...
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View'      => Illuminate\Support\Facades\View::class,
        'Cluster'   => Cluster\Foundation\Facades\Cluster::class

    ],

```

Based on the error message and my short analysis, it seems that your UrlGeneratorTrait was not loaded.

Maybe I did something wrong or forgot to load something?
If so, can you tell me what?

Thanks

**Comment by Omranic** [comment]
Well, all of `cluster-` packages are designed to work coherently within the context of `rinvex/cluster` application. It's not intended to work decoupled or outside of that context, at least for the time being. So, may be you can clone the `rinvex/cluster` and give it another shot and tell me your thoughts :)

**Comment by noxify** [comment]
WUUUU!!!! 

thanks a lot @Omranic

**Comment by Omranic** [comment]
Most welcome @noxify 
Extensive developer documentation is almost done, and supposed to be released this week.
It makes everything very clear for developers. Stay tuned ;)

**Comment by noxify** [comment]
awesome - thanks again for the fast feedback
